### ISSUE TITLE
能否在Places2 (p256) 上进行训练？

### ISSUE THREAD

**Issue by Lucky-Jay** [linghuyuhangyuan/M2S#3]
您好，我想在Places2 (p256) 上训练您提出的这个模型，我该如何做呢？

**Comment by linghuyuhangyuan** [comment]
If you want to train on custom images, please follow these steps:

1. Train a generative model for these custom images (prepare pretrained DDPM):
    - We use a lightweight diffusion model in our work. You can find it here: [P2-weighting](https://github.com/jychoi118/P2-weighting).
    - Note: Two models are required for different image resolutions. （for two different stages in inference process）

2. Use the M2S inference process:
    - Instructions are provided in our code link: [M2S](https://github.com/linghuyuhangyuan/M2S).
    - Note: `run.sh` is important! Make sure to check the hyperparameters of the trained model and load the paths of the checkpoints, among other details.

**Comment by linghuyuhangyuan** [comment]
方法已在github issue中回复。
需要告知的是：我们有尝试在places2数据集上训练和测试，但是效果不佳。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "linghuyuhangyuan/M2S"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年12月19日(星期四) 晚上8:30
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[linghuyuhangyuan/M2S] 能否在Places2 (p256) 上进行训练？ (Issue #3)





 
您好，我想在Places2 (p256) 上训练您提出的这个模型，我该如何做呢？

**Comment by Lucky-Jay** [comment]
收到，因为我使用了[RePaint](https://github.com/andreas128/RePaint)的Places2的预训练模型，在我的数据上表现比较好，但是速度太慢了，因此想试试您的方法，请问您那边有预训练好的Places2的模型可以提供给我试试嘛

**Comment by linghuyuhangyuan** [comment]
不好意思，我们没有保留，可能需要在p2-weighting的代码上重新进行训练。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "linghuyuhangyuan/M2S"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年12月19日(星期四) 晚上8:43
***@***.***&gt;;
抄送:&nbsp;"Old ***@***.******@***.***&gt;;
主题:&nbsp;Re: [linghuyuhangyuan/M2S] 能否在Places2 (p256) 上进行训练？ (Issue #3)





 
收到，因为我使用了RePaint的Places2的预训练模型，在我的数据上表现比较好，但是速度太慢了，因此想试试您的方法，请问您那边有预训练好的Places2的模型可以提供给我试试嘛

**Comment by Lucky-Jay** [comment]
嗯嗯好的，没有问题
